version: "3.9"  # optional since v1.27.0
services:
  backend:
    restart: always
    build: microservices/backend
    image: ghcr.io/keithlogan94/betasam-searchengine/backend:latest
    ports:
      - "8080:3000"
    depends_on:
      - mysql-service
  
  mysql-service:
    restart: always
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma
      links:
        - mysql-service
      environment:
        PMA_HOST: mysql-service
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        PMA_PMADB: test
        PMA_USER: root
        PMA_PASSWORD: test
      restart: always
      ports:
        - 8081:80
