name: Chart

on:
  push:
    branches:
      - master

jobs:
  helm:
    image: helm:latest
    steps:
      -
        name: Check out code
        uses: actions/checkout@v2

      - name: Build
        env:
            REGISTRY: ghcr.io
            USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.DOCKER_LOGIN_TOKEN }}
        run: |
          helm package chart 
