name: Chart

on:
  push:
    branches:
      - master

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out code
        uses: actions/checkout@v2

      - name: Build
        env:
            REGISTRY: ghcr.io
            USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.DOCKER_LOGIN_TOKEN }}
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm package chart 
